- hosts: all
  remote_user: ubuntu
  become: yes
  ignore_errors: true
  tasks:
  - name: list files
    ansible.builtin.command:
      cmd: ls -k /home/ubuntu
    register: cmd_ls
  - name: debug cmd_ls
    ansible.builtin.debug:
      var: cmd_ls